version: '3'

services:

  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_DATABASE: ingsoft3int
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./database/ingsoft3int.sql:/docker-entrypoint-initdb.d/ingsoft3int.sql
    
  backend:
    build: ./backend
    container_name: backend
    environment:
      NODE_ENV: local
    ports:
      - '8080:8080'

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on: 
      - backend
    ports:
      - '3000:3000'

 