version: '3'

services:
    
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '8800:8800'

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on: 
      - backend
    ports:
      - '3000:3000'

 