name: Build Unit Tests

on:

  push:
    branches: [main]

jobs:

  build-publish-deploy:
    
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ingsoft3int
   
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build y Correr contenedor MySQL
      run: |
          docker build -t ingsoft3int ./database
          docker run -d --name ingsoft3int -p 3306:3306
      working-directory: ./database  
          
    - name: Run backend
      run: nohup sh -c 'NODE_ENV=local node index.js' &
      working-directory: ./backend  
       
    - name: Run Tests
      run: |
          export NODE_ENV=local
          chmod +x ./node_modules/.bin/mocha
          npx mocha tests.js
      working-directory: ./backend

    - name: Run frontend
      run: |
          npm install --force
          nohup npm start &
      working-directory: ./frontend

    
   

    
