name: Build and Deploy

on:

  push:
    branches: [main]

jobs:

  build-and-publish:
    
    runs-on: ubuntu-latest
   
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build images
      run: docker-compose build
        
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Tag and Push images to Docker Hub
      run: |
          docker tag ingsoft3-integrador_backend:latest ${{ secrets.DOCKER_USERNAME }}/ingsoft3-integrador-backend:latest
          docker tag ingsoft3-integrador_frontend:latest ${{ secrets.DOCKER_USERNAME }}/ingsoft3-integrador-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ingsoft3-integrador-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ingsoft3-integrador-frontend:latest

    - name: Auth Google Cloud CLI
      uses: google-github-actions/auth@v0.4.1
      with:
          service_account_key: ${{ secrets.GCLOUD_KEY }}
          credentials_json: ${{ secrets.GCLOUD_KEY }}
          project_id: ingsoft3-integrador

    - name: Build and Push to GAR
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/ingsoft3-integrador/ingsoft3-final/frontend:latest ./frontend
        docker build -t us-central1-docker.pkg.dev/ingsoft3-integrador/ingsoft3-final/backend:latest ./backend
        docker push us-central1-docker.pkg.dev/ingsoft3-integrador/ingsoft3-final/frontend:latest
        docker push us-central1-docker.pkg.dev/ingsoft3-integrador/ingsoft3-final/backend:latest
    
    - name: Deploy Frontend
      run: |
          gcloud run deploy frontend \
            --image=us-central1-docker.pkg.dev/ingsoft3-integrador/ingsoft3-final/frontend \
            --port=3000 \
            --platform=managed \
            --region=southamerica-east1 \
            --allow-unauthenticated


    - name: Deploy Backend
      run: |
          gcloud run deploy backend \
            --image=us-central1-docker.pkg.dev/ingsoft3-integrador/ingsoft3-final/backend \
            --add-cloudsql-instances ingsoft3-integrador:us-central1:root \
            --set-env-vars "port=8080" \
            --port=8080 \
            --platform=managed \
            --region=southamerica-east1 \
            --allow-unauthenticated 
    

   

    
            
