name: Build Unit Tests

on:

  push:
    branches: [main]

jobs:

  build-publish-deploy:
    
    runs-on: ubuntu-latest
 
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Run images
      run: docker-compose up --build -d
      working-directory: ./backend

    - name: Wait for services to start
      run: sleep 30

    - name: Run Tests
      run: docker-compose exec backend npx mocha tests.js
      working-directory: ./backend
    
   

    
