name: Build Unit Tests

on:

  push:
    branches: [main]

jobs:

  build-publish-deploy:
    
    runs-on: ubuntu-latest
 
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Run images 
      run: |
          docker compose up --build -d
          sleep 30
          
    - name: Run Tests
      run: |
          export NODE_ENV=local
          chmod +x ./node_modules/.bin/mocha
          npx mocha tests.js
      working-directory: ./backend

    - name: Run backend
      run: nohup sh -c 'NODE_ENV=local node index.js' &
      working-directory: ./backend 
      
    - name: Run frontend
      run: |
          npm install --force
          nohup npm start &
      working-directory: ./frontend

    
   

    
