name: Build Unit Tests

on:

  push:
    branches: [main]

jobs:

  build-publish-deploy:
    
    runs-on: ubuntu-latest
   
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build and Run images
      run: docker-compose up --build -d
       
    - name: Run Tests
      run: |
          export NODE_ENV=local
          timeout 10 npx mocha || true
          if [ "$(timeout 10 npx mocha | grep -c '5 passing')" -eq 1 ]; then
            echo "Tests pasaron exitosamente."
          else
            echo "Los tests no pasaron. Terminando el flujo de trabajo."
            exit 1
          fi
      working-directory: ./backend

    - name: Run backend
      run: nohup sh -c 'NODE_ENV=local node index.js' &
      working-directory: ./backend  

    - name: Run frontend
      run: |
          npm install --force
          nohup npm start &
      working-directory: ./frontend

    
   

    
