name: Build and Deploy

on:

  push:
    branches: [main]

jobs:

  build-and-publish:
    
    runs-on: ubuntu-latest
   
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build images
      run: docker-compose build
        
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Tag and Push images to Docker Hub
      run: |
          docker tag ingsoft3-integrador_backend:latest ${{ secrets.DOCKER_USERNAME }}/ingsoft3-integrador-backend:latest
          docker tag ingsoft3-integrador_frontend:latest ${{ secrets.DOCKER_USERNAME }}/ingsoft3-integrador-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ingsoft3-integrador-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ingsoft3-integrador-frontend:latest

    - name: Auth Google Cloud CLI
      uses: google-github-actions/auth@v0.4.1
      with:
          service_account_key: ${{ secrets.GCLOUD_KEY }}
          credentials_json: ${{ secrets.GCLOUD_KEY }}
          project_id: ingsoft3-integrador

    - name: Deploy Frontend
      run: |
          gcloud run deploy frontend \
            --image=gcr.io/ingsoft3-integrador/ingsoft3int-frontend-gc \
            --platform=managed \
            --region=southamerica-east1 \
            --allow-unauthenticated

    - name: Deploy Backend
      run: |
          gcloud run deploy backend \
            --image=gcr.io/ingsoft3-integrador/ingsoft3int-backend-gc \
            --add-cloudsql-instances ingsoft3-integrador:us-central1:root \
            --update-env-vars INSTANCE_CONNECTION_NAME=ingsoft3-integrador:us-central1:root,DB_PASS=root,DB_USER=root,DB_NAME=ingsoft3int-database \
            gcloud beta run services add-iam-policy-binding backend \
            --member=allUsers \
            --role=roles/run.invoker
            --platform=managed \
            --region=southamerica-east1 \
            --allow-unauthenticated
