name: Build Unit Tests

on:

  push:
    branches: [main]

jobs:

  build-run-unit-tests:
    
    runs-on: ubuntu-latest
 
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Tests
      run: |
          chmod +x ./node_modules/.bin/mocha
          npx mocha tests.js
      working-directory: ./backend
      continue-on-error: false
    
   

    
